[project]
name = "kplauritzen-github-io"
version = "0.1.0"
description = "kplauritzen.dk"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.5.49",
    "pre-commit>=4.0.1",
    "pytest>=8.3.4",
    "rust-just>=1.38.0",
]
